- name: Perform an initial batch policy pull from ACS
  hosts: localhost
  gather_facts: false

  tasks:

  - name: Get policies from ACS
    vars:
      dest_path: 'acs-policy-files/'
    include_tasks:
      file: tasks/get_policies.yml
