
- name: Create policies_actual
  ansible.builtin.file:
    path: "{{ dest_path }}"
    state: directory
  changed_when: false

- name: get all policies
  uri:
    url: https://{{ acs_host }}/v1/policies
    headers:
      Authorization: "Bearer {{ acs_token }}"
    method: GET
    status_code: 200
    validate_certs: false
  register: policies
  no_log: false
  ignore_errors: true

- name: write policies
  include_tasks:
    file: get_policy.yml
  with_items: "{{ policies.json.policies }}"
  loop_control:
      loop_var: policy
