- name: Perform an initial batch policy pull from ACS
  hosts: localhost
  gather_facts: false

  vars_files:
  - vaults/vault.yml

  vars:
    acs_host: "{{ vaulted_acs_host }}"
    acs_token: "{{ vaulted_acs_token }}"

  tasks:

  - name: Get policies from ACS
    vars:
      dest_path: '../acs-policy-files'
    include_tasks:
      file: tasks/get_policies.yml
