name: ansible-lint-and-push
on: [push, pull_request]

jobs:
  build:
    name: Ansible Lint and Update # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed for progressive mode to work

      - name: Run ansible-lint
        # replace `main` with any valid ref, or tags like `v6`
        uses: ansible/ansible-lint-action@v6.14.4
        # optional:
        with:
          path: "-cansible-lint"  # <-- only one value is allowed